#开启springboot的debug模式
#debug: true

spring:
  profiles:
    #激活 1.application-dev.yml 配置文件的使用（此处无）OR 2.激活：下方第二文档快-dev）
    active: dev

---
#第二文档快：开发环境----------------

#HTTPS配置，和HTTP不可同时配置
server:
  #443
  port: 443
  ssl:
    key-store: src/main/resources/tomcat.keystore
    key-store-password: 123456
    key-alias: tomcat
    key-store-type: JKS
  servlet:
    # 应用的访问路径
    context-path: /
  tomcat:
    # 存放Tomcat的日志目录    /root/myhome
    #    basedir: C:/tomcat
    basedir: /root/myhome
    accesslog:
      # 开启日志记录
      enabled: true
      # 访问日志存放目录
      directory: logs
    # tomcat的URI编码
    uri-encoding: UTF-8

    #日志
#logging:
  #level:
    # 修改包-com.mine.west 的日志界别为 trace
    #com.mine.west: debug


spring:
  # 定义环境： dev环境
  profiles: dev

  #模板引擎配置
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    # 禁用缓存 ---改动html即时刷新
    cache: false
    servlet:
      content-type: text/html

  jackson:
    time-zone: GMT+8
    #把从前端得到的此格式数据 转换为date类型
    date-format: yyyy-MM-dd HH:mm:ss

  # 文件上传
  servlet:
    multipart:
      # 单个文件大小
      max-file-size:  5MB
      # 设置总上传的文件大小
      max-request-size:  10MB

  #。。。。
  devtools:
    restart:
      # 热部署开关
      enabled: true

  #缓存设置
  redis:
    host: 127.0.0.1
    port: 6379
    password: 123456
    # 连接超时时长（毫秒）
    timeout: 0
    jedis:
      pool:
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1


  #静态文件配置
  resources:
    static-locations: classpath:/static,classpath:/META-INF/resources,classpath:/templates/,classpath:/XXXX/,file:/XXXX/
  #jdbc配置  （39.101.199.3）
  datasource:
    url: jdbc:mysql://39.101.199.3:3306/wedoveDatabase?useUnicode=true&characterEncoding=UTF-8&useSSL=true&serverTimezone=Etc/GMT-8&tinyInt1isBit=false
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

#mybatis配置
mybatis:
  #映射文件路径
  mapper-locations: classpath:mapper/*.xml
  #模型所在的包名
  type-aliases-package: com.mine.west.models
  #dao类和实体类的位置
  #project: src/main/java
  #mapper.xml 文件的位置
  #resources: src/main/resources

# Shiro
shiro:
  user:
    # 登录地址
    loginUrl: /account/login
    # 权限认证失败地址
    unauthorizedUrl: /account/unauth
    #被踢出后重定向到的地址
    kickoutUrl: /account/kickout
    # 首页地址
    indexUrl: /index
    # 验证码开关
    captchaEnabled: false
    # 验证码类型 char
    captchaType: char
  cookie:
    # 设置Cookie的域名 默认空，即当前访问的域名
    domain:
    # 设置cookie的有效访问路径
    path: /
    # 设置HttpOnly属性
    httpOnly: true
    # 设置Cookie的过期时间，天为单位
    maxAge: 15
  session:
    # Session超时时间，-1代表永不过期（默认30分钟）
    expireTime: 30
    # 同步session到数据库的周期（默认1分钟）
    dbSyncPeriod: 1
    # 相隔多久检查一次session的有效性，默认就是10分钟
    validationInterval: 10
    # 同一个用户最大会话数，比如2的意思是同一个账号允许最多同时两个人登录（默认-1不限制）
    maxSession: 1
    # 踢出之前登录的/之后登录的用户，默认踢出之前登录的用户
    kickoutAfter: false
    # 过期时间(秒)
    timeout: 7200


#邮件配置
email:
  host: smtp.sina.com
  from: xydflxy@sina.com
  user: www.wedove.com
  pwd: 2b0bbf79b6c62665

# 防止XSS攻击
xss:
  filter:
    # 过滤开关
    enabled: true
    # 排除链接（多个用逗号分隔）--> 静态资源 + /home/reply:表示数据库存放原回复，显示在前端时再过滤
    excludes: /js/*,/img/*,/ajax/*,/webjars/*,/swagger-resources/*,/v2/*,/swagger-ui.html/*,/account/*

csrf:
  filter:
    #是否开启-防止csrf攻击
    enabled: true
    # 排除链接（多个用逗号分隔）
    excludes: /account/login,account/register/*,/webjars/*,/swagger-resources/*,/v2/*,/swagger-ui.html/*

#swagger开关
swagger:
  enable: true

#---
#第三文档快

#server:
#  port: 8082
#
#spring:
#  # 定义环境： dev环境
#  profiles: dev



